# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  dbutilstest:
    Url: jdbc:hsqldb:mem:dbutilstest
    Driver: org.hsqldb.jdbc.JDBCDriver
    UserName: sa
    Password: ${decrypt:}
