# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  comicworld_hsqldb:
    Url: jdbc:hsqldb:mem:comicworld
    Driver: org.hsqldb.jdbc.JDBCDriver
    UserName: comicworld
    Password: ${decrypt:}
  comicworld_mssql:
    Url: jdbc:sqlserver://localhost:14033;databaseName=comicworld
    Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    UserName: comicworld
    Password: ${decrypt:/ONFjKtA0h6caXsEaRP29A==}
