Databases:
  comicworld_hsqldb:
    Url: jdbc:hsqldb:mem:comicworld
    Driver: org.hsqldb.jdbc.JDBCDriver
    UserName: comicworld
    Password: ${decrypt:}
  comicworld_mssql:
    Url: jdbc:sqlserver://localhost:14033;databaseName=comicworld
    Driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    UserName: comicworld
    Password: ${decrypt:}
